### ISSUE TITLE
Cannot use env before fastify has started

### ISSUE THREAD

**Issue by Javarome** [fastify/fastify-env#108]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.18.1

### Plugin version

2.1.1

### Node.js version

15.12

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.5

### Description

As described in the documentation, we have to wait for environment variables to be read:
```
fastify
  .register(fastifyEnv, options)
  .ready((err) => {
    if (err) console.error(err)
    // fastify.config is available!
    console.log(fastify.config) // or fastify[options.confKey]
  })
```
However a typical usage of environment reading is to parameterize other plugins, and no more plugins can be registered after ready(), which states that the fastify server has been started.

### Steps to Reproduce

Try to register another plugin in ready callback:
```
const server = fastify.register(fastifyEnv, options) 
server.ready((err) => {
    if (err) console.error(err)
    // fastify.config is available!
    server.register(otherPlugin, {param: fastify.config.someParam}) // ERROR: root plugin has already booted
  })
```

### Expected Behavior

Resolved env should be available to other plugins, before server listening.

**Comment by zekth** [comment]
You can do something like this:
```js
let app = require('fastify')({ logger: true });
const fastifyEnv = require('fastify-env');
app.register(fastifyEnv, {
  schema: {
    type: 'object',
    required: ['AWS_DEFAULT_REGION'],
    properties: {
      AWS_DEFAULT_REGION: { type: 'string' }
    }
  }
});
app.register(async (instance, options) => {
  console.log(instance.config);
});
app.listen((err) => {
  if (err) console.error(err);
  // fastify.config is available!
});

```

Which will prompt:
```
{ AWS_DEFAULT_REGION: 'us-east-2' }
{"level":30,"time":1627987630171,"pid":7276,"hostname":"XXXXX","msg":"Server listening at http://127.0.0.1:52934"}
```

You can only register plugins **BEFORE** setting the instance as ready. That's why you have this issue.

**Comment by climba03003** [comment]
`fastify` the plugin in asynchronously. You need to be sure the plugin is registered in order, so the next plugin can get the detail from previous one.

For example the below format can ensure you previous plugin is set.
```js
// async-await method 1
await fastify.register(fastifyEnv)
// fastify.config can be used in here

// async-await method 2
fastify.register(fastifyEnv)
await fastify.after()
// fastify.config can be used in here

// callback method 1
fastify.register(fastifyEnv).after(function() {
  // fastify.config can be used in here
})

// callback method 2
fastify.register(fastifyEnv)
fastify.register(somthingElse, function() {
  // fastify.config can be used in here
  return option
})
```

**Comment by danechitoaie** [comment]
Had same issue and the above messages helped fix it. Thank you.
