### ISSUE TITLE
Exporting 'env-schema' dependency needed

### ISSUE THREAD

**Issue by eeni** [fastify/fastify-env#133]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Using the ``fastify-env`` plugin in our ``fastify`` project I came on a scenario when I should load the env variables before I boot the application and register the plugin to the ``fastify`` instance (currently on the database migration part, on which I should access the env variables). I can use ``env-schema`` with the existing options that I have build for the plugin but it would be adding an extra dependency, keeping in mind that plugin is already using it. Being able to get the ``env-schema`` from the plugin library would help me to solve the issue.

**Comment by mcollina** [comment]
The only way to do that is to use env-schema directly. I would just drop the use of this plugin.
