### ISSUE TITLE
fastify-env does not support Fastify version 4.0

### ISSUE THREAD

**Issue by jutunen** [fastify/fastify-env#147]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.1

### Plugin version

2.2.0

### Node.js version

16.13.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Description

"FastifyError","code":"FST_ERR_PLUGIN_VERSION_MISMATCH","statusCode":500},"msg":"fastify-plugin: fastify-env - expected '3.x' fastify version, '4.0.1' is installed"}

### Steps to Reproduce

1. Install fastify 4.0.1
2. Install fastify-env
3. Start your server
4. Server won't start

**Comment by climba03003** [comment]
Please install `@fastify/env`
