### ISSUE TITLE
Different way to expand the FastifyInstance which works better for me.

### ISSUE THREAD

**Issue by kasir-barati** [fastify/fastify-env#161]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

You can see that in my solution you do can add the config attribute and expand the `FastifyInstance` interface much easier. Here is my implementation: https://github.com/kasir-barati/fastify-worktime/blob/main/src/types/fastify-config.type.d.ts

### Suggestion

Change the doc to advocate this solution since it is easier and better IMO

**Comment by jsjoeio** [comment]
Does this still work? I'm having a hard time getting TypeScript to recognize `config` on my fastify instance

**Comment by pedroapfilho** [comment]
It doesn't seem to work

**Comment by kasir-barati** [comment]
@jsjoeio @pedroapfilho Sorry guys, I look into it and update you

**Comment by kasir-barati** [comment]
![image](https://user-images.githubusercontent.com/73785723/235340598-9a88c9fe-ef96-4b15-b902-b45ec6b75834.png)

I just cloned my repo and test it. But I also used pnpm this time since I migrated to pnpm :smile: 

But I do not believe that was relevant. Anyway, as you can see in the screenshot intelisence in code-oss works. Can you tell me what you meant by "It doesn't seem to work"

**Comment by mcollina** [comment]
I don't understand the difference to what we do.

**Comment by kasir-barati** [comment]
> I don't understand the difference to what we do.

No intellisense in VSCode was bugging me. So I decided to take matters on my own hand and here is the result.

**Comment by mcollina** [comment]
I still don't understand what would be the difference to what we are recommeding.

**Comment by kasir-barati** [comment]
@mcollina Nothing fancy :sweat_smile:, it's just my affection towards intellisense.

But thanks for following me and answering my request even due it **seems** that you do not see any value in it.

**Comment by mcollina** [comment]
> But thanks for following me and answering my request even due it seems that you do not see any value in it.

@kasir-barati this is incorrect. I don't understand what is the difference with what we are doing/recommeding and what would be the proposed fix for this issue. I would be happy to see a pull request if you think it's a valuable contribution.

**Comment by Uzlopak** [comment]
@kasir-barati 

But we have documented it already here

https://github.com/kasir-barati/fastify-worktime/blob/main/src/types/fastify-config.type.d.ts
