### ISSUE TITLE
Custom data with env

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify-env#2]
I like this utility!
I think could be nice to have `process.env` and some optional data together instead of data *or* `process.env`.

```js
const data = Object.assign(opts.data || {}, process.env)
```

In this way you can share some custom config and `process.env` at the same time in the same place :)
What do you think?

**Comment by allevo** [comment]
Thanks!!

Do you mean some kind or merging?
And if I don't want to use `process.env` at all?

Maybe an array of data source can be specified?

```js
const options = {
  schema: schema,
  data: [ obj1, obj2, process.env ] // ordered!
}
```
`options.data`  has `process.env` as default?

Anyway I like this proposal! Particularly if applied to `fastify-cli` utils!

**Comment by delvedor** [comment]
`process.env` is a powerful thing I would like to have it as default.
We could add an options such as `env: false` to avoid it.

I like the array of data sources!
You could use [`xtend`](https://www.npmjs.com/package/xtend) to merge the data, is an awesome library.

Furthermore I think that `process.env` should be never overwritten, so you should always merge it at the end.

**Comment by allevo** [comment]
Discussion moved to #3
