### ISSUE TITLE
[DISCUSSION] Any consideration on incorporating .env file loader into this plugin?

### ISSUE THREAD

**Issue by joebartels** [fastify/fastify-env#27]
I end up using node-dotenv in a lot of projects to load a .env file.
I'm doing that manually in my fastify projects also
https://github.com/motdotla/dotenv

thoughts?

**Comment by mcollina** [comment]
It might be actually a good idea. What do you think @allevo?

**Comment by allevo** [comment]
Hi!
  thanks for sharing your ideas! Sharing ideas makes the world better!
That feature is very nice and I'd like to create new fastify plugin for that.

```
function handler (request, reply) {
  // this.config contains all environment variables loaded by 'fastify-dotenv'
  // checkd by 'fastify-env'
  reply.send(this.config)
}

fastify
  .register(require('fastify-dotenv`))
  .register(require('fastify-env`), { schema: { ... } })
  .get('/', handler)
```

In this case we able to use the dotenv loader without 'fastify-env' package and vice versa.

**Comment by joebartels** [comment]
That seems fair. I really like fastify-env's current functionality as-is. 
My only critique with a new plugin is that the configuration for dotenv is very minimal and in many cases it's only:
```
require('dotenv').config();
```
And so if that's not _too_ little _(of course it would allow options to be passed to `.config(opts)` also)_ for a new plugin then sounds good to me 👍

**Comment by mcollina** [comment]
I think fastify-dotenv should wrap this, but that’s my taste.

**Comment by joebartels** [comment]
cool! Would love to. 

My first thought is to expose 2 additional options:
```js
...
dotenv: { type: 'boolean', default: false }, // to enable/disable loading the dotenv library 
dotenvConfig: { type: 'object' } // to pass along `{path, encoding}` options to dotenv library
```

If there are no objections I'll go that direction.
If anything comes up after I PR I'll address any concerns on the review!
