### ISSUE TITLE
sync loading

### ISSUE THREAD

**Issue by MomenNano** [fastify/fastify-env#63]
Is there any way I can make sure all the env are loaded?

when I register the plugin I can't call fastify.config and its say undefined, even fastify.config.PORT

so I make .ready to make sure it load first and then calling start() function which have fastify.config.PORT. this work for me, but when I tried to use it with another plugins like fastify-mongodb it makes error say **root plugin has already booted**

`fastify.register(fastifyEnv, options).ready(err => {
  if (err) {
    console.log(err)
  }
 fastify.register(require('fastify-mongodb'), {
    forceClose: true,
    url: fastify.env.DB_URL
  })
  start()
})`

I just want to find is there any way I can call this synchronously to make sure it load all my env variables. 

- *node version*: 12
- *fastify version*: >=2.14.0
- *os*: Windows

**Comment by Dec-** [comment]
How did you fix it?

I have same issue and cant figure it out.
