### ISSUE TITLE
Typescript Typings

### ISSUE THREAD

**Issue by climba03003** [fastify/fastify-env#69]
## 🚀 Feature Proposal

Add the missing typescript typing.

## Motivation

Better integration with typescript.

## Example

No additional file like ```fastify-env.d.ts``` is needed for typescript project.

**Comment by climba03003** [comment]
I have checked it is just a wrapper plugin for ```env-schema```.

The possible solution will be
1. create PR to ```env-schema```, then add the typing there and reflect the typing to this plugin.
2. just add the typing here.

**Comment by mcollina** [comment]
I would create the types in env-schema first!
