### ISSUE TITLE
[Regression] AJV validation error does not render the responsible field name anymore

### ISSUE THREAD

**Issue by jeandat** [fastify/fastify-env#72]
## 🐛 Bug Report

When AJV validation fail, you see an error like that: "Error: should be number".
In that case for instance the field is configured as a number.

In previous versions (don't know when it stopped working, didn't search), you would have a normal message that mention the field name responsible.

## To Reproduce

```js
server.register(require('fastify-env') as any, { schema });
```
with `schema` being whatever ajv schema is valid.

## Expected behavior

I would like to know which field is in error. By default the field name should be used.

## Your Environment

- *node version*: 12.18.3
- *fastify version*: 3.5.1
- *fastify env version*: 2.0.1
- *os*: Mac

**Comment by Eomm** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
